### PR TITLE
Reverse displayed rank list

### LINKED ISSUE #28: [bug] Ranks need to be displayed in reverse order
**Describe the bug**
.rank set shows
```
Invalid rank, available ranks:
 • Iron1
 • Iron2
 • Iron3
 • Bronze1
 • Bronze2
 • Bronze3
 • Silver1
 • Silver2
 • Silver3
 • Gold1
 • Gold2
 • Gold3
 • Platinum1
 • Platinum2
 • Platinum3
 • Diamond1
 • Diamond2
 • Diamond3
 • Immortal1
 • Immortal2
 • Immortal3
 • Radiant
```

**Expected behavior**
It should show top rank at the top instead of at the bottom

**Additional context**

### PR DESCRIPTION
**Pull request by BrandonWLee**
Closes #28 
ez

### CODE REVIEW

File: commands/rank.js [hunk 1]
```diff
@@ -110,7 +110,7 @@ function sendHelp(channel) {
 }
 
 function sendRanks(channel) {
-  return channel.send("Invalid rank, available ranks:\n" + " • " + ALLOWED_RANKS.join("\n • "), {code: "asciidoc"});
+  return channel.send("Invalid rank, available ranks:\n" + " • " + ALLOWED_RANKS.reverse().join("\n • "), {code: "asciidoc"});
```
Comment (mynameisivan) [inline commands/rank.js:113]: Reverse the constant once :)
